# Generated by Django 6.0.1 on 2026-01-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_description',
            field=models.TextField(null=True),
        ),
    ]
