# Generated by Django 6.0.1 on 2026-01-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_candidateprofile_linkedin_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='website',
            new_name='website_link',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='industry',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='about_company',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
