# Generated by Django 6.0.1 on 2026-01-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_url',
            field=models.URLField(default='https://example.com/old-resume.pdf'),
            preserve_default=False,
        ),
    ]
