# Generated by Django 6.0.1 on 2026-01-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_jobapplication_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('recieved', 'Recieved')], null=True),
        ),
    ]
