# Generated by Django 6.0.1 on 2026-05-29 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_resumechunk_embedding'),
        ('applications', '0004_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='ai.resume'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending_approval', 'Pending Cover Letter Review'), ('approved', 'Approved - Ready to Submit'), ('applied', 'Applied via Automation'), ('failed', 'Automation Error')], default='new', max_length=20, null=True),
        ),
    ]
