# Generated by Django 6.0.1 on 2026-01-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
