# Generated by Django 6.0.1 on 2026-05-29 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_resumechunk_embedding'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drafted_cover_letter', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Cover Letter Review'), ('APPROVED', 'Approved - Queueing Submission'), ('APPLIED', 'Application Successfully Submitted'), ('REJECTED', 'Rejected by User'), ('FAILED', 'Automation Error')], default='PENDING_APPROVAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.resume')),
            ],
            options={
                'unique_together': {('resume', 'job')},
            },
        ),
    ]
