# Generated by Django 6.0.1 on 2026-05-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_automatedapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutomatedApplication',
        ),
    ]
