# Generated by Django 6.0.1 on 2026-01-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_experience_level_job_work_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
