# Generated by Django 6.0.1 on 2026-02-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_job_type_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('intern', 'Intern'), ('entry', 'Entry Level'), ('senior', 'Senior Level')], max_length=30, null=True),
        ),
    ]
