# Generated by Django 6.0.1 on 2026-05-28 05:29

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
    ]
