# Generated by Django 6.0.1 on 2026-05-28 06:29

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_resumechunk_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=3072, null=True),
        ),
    ]
